package com.ajouin.ajouin_be.domain.news.domain

object InstagramAccounts {
    val instagramAccounts: Map<String, String> = mapOf(
        "총학생회" to "ajou_council",
        "공과대학" to "ajou_danbi_41",
        "정보통신대학" to "eroom_ajou",
        "소프트웨어융합대학" to "soone_ajou",
        "자연과학대학" to "ajou_natural_science",
        "경영대학" to "ajou_hashtag",
        "인문대학" to "ajou_linelac",
        "사회과학대학" to "social_science_ajou",
        "의과대학" to "ausom_seoro",
        "간호대학" to "ajou_nursing_bada",
        "약학대학" to "ajou_pharmacy",
        "기계공학과" to "ajou_mecha",
        "산업공학과" to "ajou_fresh43",
        "응용화학생명공학과" to "ajou_acbe",
        "화학공학과" to "ajou_ace",
        "첨단신소재공학과" to "ajou_sinsojae",
        "건설시스템공학과" to "ajou_civil",
        "교통시스템공학과" to "ajou_its",
        "건축학과" to "ajouarchi_able",
        "AI모빌리티공학과" to "ajou._.aim",
        "전자공학과" to "ajou_electronics",
        "지능형반도체공학과" to "ajou_isemiconductor",
        "사이버보안학과" to "ajou_cloud",
        "디지털미디어학과" to "ajou_media.25",
        "수학과" to "math_of_ajou_new",
        "물리학과" to "ajou.physics.council",
        "화학과" to "ajou_chemistry",
        "생명과학과" to "ajou_bio",
        "경영학과" to "ajou_business",
        "글로벌경영학과" to "ajou_btopia",
        "국어국문학과" to "ajou_mongle",
        "영어영문학과" to "ajou_blooming",
        "불어불문학과" to "aufr_officiel",
        "사학과" to "ajou_his",
        "문화콘텐츠학과" to "ajou_shamrock",
        "경제학과" to "ajou_economics",
        "행정학과" to "ajou_admin",
        "심리학과" to "ajou_psychology_",
        "사회학과" to "ajou_sociology",
        "정지외교학과" to "ajou_psd"
    )
}